TTAssignment/TTAssignment/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TTAssignment.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

TTAssignment/TTAssignment/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TTAssignment.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

TTAssignment/TTAssignment/Pages/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TTAssignment.Core;
using TTAssignment.Data;

namespace TTAssignment.Pages.Employees
{
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeData _employeeData;
        public DeleteModel(IEmployeeData employeeData)
        {
            this._employeeData = employeeData;
        }
        public Employee Employee { get; set; }

        public IActionResult OnGet(int EmployeeId)
        {
            Employee = _employeeData.GetEmployee(EmployeeId);
            if(Employee ==null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();

        }

        public IActionResult OnPost(int EmployeeId)
        {
            var emp  = _employeeData.Delete(EmployeeId);
            _employeeData.Commit();

            if (emp == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{emp.FirstName} deleted..";
            return RedirectToPage("./Employeelist");
        }
    }
}

TTAssignment/TTAssignment/Pages/Employees/EmployeeDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TTAssignment.Core;
using TTAssignment.Data;

namespace TTAssignment.Pages.Employees
{
    public class EmployeeDetailModel : PageModel
    {
        private IEmployeeData _employeeData;
        public Employee employee { get; set; }

        [TempData]
        public string EmployeeSavedMsg { get; set; }

        public EmployeeDetailModel(IEmployeeData employeeData)
        {
            _employeeData = employeeData;
        }
        public IActionResult OnGet(int EmployeeId)
        {

            employee = _employeeData.GetEmployee(EmployeeId);
            if(employee == null)
            {
                return RedirectToPage("./NotFound");
            }
            else
            {
                return Page();
            }
            

        }
    }
}

TTAssignment/TTAssignment/Pages/Employees/EmployeeEdit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using TTAssignment.Core;
using TTAssignment.Data;

namespace TTAssignment.Pages.Employees
{
    public class EmployeeEditModel : PageModel
    {
        private IEmployeeData _employeeData;
        private IHtmlHelper _htmlHelper;

        [BindProperty]
        public Employee Employee { get; set; }

        public IEnumerable<SelectListItem> EmpTypes { get; set; }
        public EmployeeEditModel(IEmployeeData employeeData, IHtmlHelper htmlHelper)
        {
            _employeeData = employeeData;
            this._htmlHelper = htmlHelper;
        }
        public IActionResult OnGet(int? EmployeeId)
        {
            EmpTypes = _htmlHelper.GetEnumSelectList<EmployeeType>();

            if (EmployeeId.HasValue)
            {
                Employee = _employeeData.GetEmployee(EmployeeId.Value);
            }
            else
            {
                Employee = new Employee();
            }

            if (Employee == null)
                return RedirectToPage("./NotFound");
            else
                return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                EmpTypes = _htmlHelper.GetEnumSelectList<EmployeeType>();

                return Page();
            }

            if (Employee.EmployeeId > 0)
                Employee = _employeeData.Update(Employee);
            else
            {
                _employeeData.Add(Employee);
            }
            _employeeData.Commit();
            TempData["EmployeeSavedMsg"] = "Employee Saved Sucessfully..";
            return RedirectToPage("./EmployeeDetail", new { employeeId = Employee.EmployeeId });

        }
    }
}

TTAssignment/TTAssignment/Pages/Employees/Employeelist.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using TTAssignment.Core;
using TTAssignment.Data;

namespace TTAssignment.Pages.Employees
{
    public class EmployeelistModel : PageModel
    {
        private IConfiguration _config;
        private IEmployeeData _employeedata;

        public string EmployeeHeader = string.Empty;

        [BindProperty(SupportsGet =true)]
        public string SearchTerm { get; set; }

        public IEnumerable<Employee> lstEmployees { get; set; }
        public EmployeelistModel(IConfiguration config, IEmployeeData employeedata)
        {
            _config = config;
            _employeedata = employeedata;
        }
        public void OnGet()
        {
            EmployeeHeader = _config["EmployeeHeading"];
            lstEmployees = _employeedata.GetEmployeeByName(SearchTerm);

        }
    }
}

TTAssignment/TTAssignment/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TTAssignment.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TTAssignment/TTAssignment/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TTAssignment.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TTAssignment/TTAssignment/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TTAssignment.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TTAssignment/TTAssignment/ViewComponents/EmployeeCountViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TTAssignment.Data;

namespace TTAssignment.ViewComponents
{
    public class EmployeeCountViewComponent: ViewComponent
    {
        private readonly IEmployeeData _employeedata;
        public EmployeeCountViewComponent(IEmployeeData employeedata)
        {
            _employeedata = employeedata;
        }

        public IViewComponentResult Invoke()
        {
            var count = _employeedata.EmployeeCount();
            return View(count);
        }
    }
}

TTAssignment/TTAssignment/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

TTAssignment/TTAssignment/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TTAssignment/TTAssignment/Pages/Employees/Delete.cshtml
@page "{EmployeeId}"
@model TTAssignment.Pages.Employees.DeleteModel
@{
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2>Delete !!</h2>
    <div class="alert alert-danger">
        Are you sure you want to delete @Model.Employee.FirstName ?
    </div>
    <form method="Post">
        <button type="submit" class="btn btn-danger">Yes!</button>
        <a asp-page="Employeelist" class="btn btn-default">Cancel</a>
    </form>
</body>
</html>

TTAssignment/TTAssignment/Pages/Employees/EmployeeDetail.cshtml
@page
@model TTAssignment.Pages.Employees.EmployeeDetailModel
@{
    ViewData["Title"] = "EmployeeDetail";
}

<h2>EmployeeDetail</h2>
<div>
    Employee-ID : @Model.employee.EmployeeId;
</div>
<div>
    FirstName : @Model.employee.FirstName;
</div>
<div>
    LastName: @Model.employee.LastName;
</div>
<div>
    Type : @Model.employee.EmpType;
</div>

@if(Model.EmployeeSavedMsg != null)
{
    <div class="alert alert-info">@Model.EmployeeSavedMsg</div>
}

<a  asp-page="./Employeelist" class=" btn btn-primary"> All Employees</a>

TTAssignment/TTAssignment/Pages/Employees/EmployeeEdit.cshtml
@page "{EmployeeId:int?}"
@model TTAssignment.Pages.Employees.EmployeeEditModel
@{
    ViewData["Title"] = "EmployeeEdit";
}

<h2>EmployeeEdit</h2>
<form method="post">
    <input type="hidden" asp-for="Employee.EmployeeId" />

    <div class="form-group">
        <label asp-for="Employee.FirstName"></label>
        <input asp-for="Employee.FirstName" class="form-control" />
        <span class="text-danger" asp-validation-for="Employee.FirstName"></span>

    </div>
    <div class="form-group">
        <label asp-for="Employee.LastName"></label>
        <input asp-for="Employee.LastName" class="form-control" />

    </div>
    <div class="form-group">
        <label asp-for="Employee.EmpType"></label>
        <select class="form-control" asp-for="Employee.EmpType" asp-items="Model.EmpTypes">
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

TTAssignment/TTAssignment/Pages/Employees/Employeelist.cshtml
@page
@model EmployeelistModel
@{
    ViewData["Title"] = "Employees";
}
<h1>@Model.EmployeeHeader</h1>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>

@foreach (var employee in Model.lstEmployees)
{
    <partial name="_EmpWidget" model="employee" />
}
<a asp-page="./EmployeeEdit" class="btn btn-primary"> Add Employee</a>

TTAssignment/TTAssignment/Pages/Employees/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>NotFound</h2>
<div>
    Employee not found...
</div>
<a asp-page="./Employeelist" class=" btn btn-primary"> All Employees</a>

TTAssignment/TTAssignment/Pages/Employees/_EmpWidget.cshtml
@using TTAssignment.Core
@model Employee

<div class="panel panel-default">

    <div class="panel-heading">
        <h3>@Model.FirstName</h3>
    </div>
    <div class="panel-body">
        <span>LastName : @Model.LastName</span>
        <span>EmpType : @Model.EmpType</span>
        <span>EmpId : @Model.EmployeeId</span>
    </div>
    <div class=" panel-footer">
        <a class="btn btn-lg" asp-page="./EmployeeDetail" asp-route-EmployeeId="@Model.EmployeeId">
            <i class=" = glyphicon glyphicon-zoom-in"></i>
        </a>
        <a class="btn btn-lg" asp-page="./EmployeeEdit" asp-route-EmployeeId="@Model.EmployeeId">
            <i class=" = glyphicon glyphicon-edit"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Delete" asp-route-EmployeeId="@Model.EmployeeId">
            <i class=" = glyphicon glyphicon-trash"></i>
        </a>
    </div>

</div>

TTAssignment/TTAssignment/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

TTAssignment/TTAssignment/Pages/Shared/Components/EmployeeCount/Default.cshtml
@model int
@if (User.Identity.IsAuthenticated)
{
    <div class="well">
        There are @Model employees available in the System. <a asp-page="/Employees/Employeelist"> Here is the list..</a>
    </div>
}

TTAssignment/TTAssignment/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TTAssignment</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">TTAssignment</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                    <li><a asp-page="/Employees/Employeelist">Employee</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <vc:employee-count></vc:employee-count>
            <p>&copy; 2020 - TTAssignment</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>